name:                tron-lines
version:             0.1.0.0
github:              "gfarrell/tron-lines"
license:             BSD3
author:              "Gideon Farrell"
maintainer:          "gideon@gtf.io"
copyright:           "2021 Gideon Farrell"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gfarrell/tron-lines#readme>

dependencies:
- base >= 4.7 && < 5
- random >= 1.1 && < 2
- random-shuffle == 0.0.4
- hspec >= 2.7 && < 3
- ansi-terminal >= 0.10 && < 0.11

library:
  source-dirs: src

executables:
  tron-lines-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tron-lines

tests:
  tron-lines-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tron-lines
    - hspec
